### ISSUE TITLE
Charts do not render in RStudio IDE (remains to "unwind")

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/altair#11]
As of now, a chart will render in a browser, but not in the RStudio IDE. 

@AliciaSchep notes that she found it necessary to include ES6 promise and symbol polyfills.

**Comment by ijlyttle** [comment]
Progress: Thanks to @AliciaSchep's advice, now renders in RStudio IDE window, but not yet inline in Rmd notebooks.

**Comment by AliciaSchep** [comment]
With update, I still don't see the plots in rstudio viewer (or notebook).  Weirdly if I try using same version of vega.js just not minified it seems to show up (had tried that version in hopes it would be easier to debug) in rstudio viewer, although still not in the notebook

I think the notebook issue is some kind of javascript issue and not a print/knit_print issue because I get the white box where the widget should go and then some javascript errors in console window

**Comment by ijlyttle** [comment]
That **is** weird that the non-minified version of vega.js just works. Do you think we should switch to the non-minified version with the package itself?

Thanks for poking around on the inline issue and throwing light on the javascript. I'll do the same over the weekend, maybe one of us can shake it loose 🙏

**Comment by AliciaSchep** [comment]
I think I have made some progress in understanding why there is an error with 'inline' display in htmlwidgets. This is a super weird bug.

Rstudio adds some javascript code into the header of the html for the notebook chunk view:

![javascript_added](https://user-images.githubusercontent.com/6809790/38597846-b4f0e6f2-3d0e-11e8-8964-a453b41edc48.png)

(See [this search of rstudio repo](https://github.com/rstudio/rstudio/search?utf8=%E2%9C%93&q=wheel&type=) for some clues on how rstudio is doing this adding)

But that javascript also gets added to vega-embed (using the non-minified for debugging purposes).

![inserted_javascript_wrong_place](https://user-images.githubusercontent.com/6809790/38597853-c7ddf11a-3d0e-11e8-9e49-a9371fd24b32.png)

It seems to add it there because that part of the code is creating some html and has "head" tags that the method for inserting the javascript probably uses to decide where to insert stuff:

![where_it_gets_inserted](https://user-images.githubusercontent.com/6809790/38597881-e41f4a86-3d0e-11e8-9553-3bfc41e0768a.png)

This insertion leads to an error (the console.log error points to that particular section in the vega-embed script).

I think this is a bug on rstudio's part -- it should not insert its javascript snippet into other javascript.  I will file a ticket there, but will first want to put together a minimal example to share.

**Comment by ijlyttle** [comment]
Nice catch! I am going to need to sit down with a cup of coffee to wrap my head around it. From what I understand so far, the fact that there is a vega-embed snippet is consistent with the superficial question I was asking myself: "why does this work for leaflet, but not for us"?

I agree with you that rstudio should take this into account (assuming this is the culprit). Let me know if I can be of help!

**Comment by AliciaSchep** [comment]
I have confirmed that the "head" tags are the issue -- editing the vegaEmbed line with the head tags as:
```js
var header = "<html><he"+"ad>" + sourceHeader + "</he" +"ad><body><pre><code class=\"json\">";
```
So that the full string is no longer present fixes the issue!  :tada: :tada: :tada:

![notebook_success](https://user-images.githubusercontent.com/6809790/38653811-5669395a-3dc1-11e8-868c-a1d96c99b927.png)

I'll still file a bug with rstudio.  But in the meantime, would it be okay to put in a PR with a modified vega-embed that works with the notebook?  I can try to make the modification be something that happens programmatically after the download of vega-embed by the rmarkdown in data-raw.

**Comment by ijlyttle** [comment]
🎉 🎉 🎉, indeed! Nicely done!

If I understand correctly, you are denaturing the vega-embed code to avoid the collision. Does this have any effect in the other rendering scenarios like the RStudio viewer pane or R Markdown documents?

It would be great if you could make a PR. As you suggest, it would be nice to have a programmatic download-and-modification. If that turns out to be burdensome, I'm sure it would be fine to modify the manifest to include `vega-embed-aschep.js` or the like, making the modification by hand - especially if RStudio make their fix reasonably quickly.

If RStudio aren't able to make a fix quickly, I think it becomes more interesting to have a reproducible fix.

At any rate, please make a PR as you see fit. 

Thanks!

**Comment by AliciaSchep** [comment]
As far as I can tell the change has no ill effects on other outputs -- the change is to break up the string from "head" into "he" + "ad" (which will get added up into "head" by the javascript) so in theory should have the same exact behavior (but avoid being caught by rstudio's parser for head tags)

**Comment by mdequeljoe** [comment]
hi @AliciaSchep  @ijlyttle - altair in R looks really cool!
just wanted to say that i came across this same issue working on something [similar](https://github.com/mdequeljoe/vl) so this was quite helpful. So thanks for this! Since I use this same workaround will give credit for this in the description file if you agree.

**Comment by ijlyttle** [comment]
Hi Matthew, 

On the question of agreement, of course I defer to @AliciaSchep, who came up with the workaround.

It is great to see more work in this area - I take as an issue on my end to make a link to your work.

One of the things we have planned is to split the package into two (#49), so the renderer would stand apart from the spec-generator. This way, you - or anyone - would be welcome to import/export the rendering functions.

**Comment by AliciaSchep** [comment]
@mdequeljoe whatever you feel is appropriate is fine by me! Thanks for sharing your project, looks like an interesting approach. 

One thing we could make use of in altair (or the future split-off renderer) @ijlyttle is the "dots" replacement that `vl` does (https://github.com/mdequeljoe/vl/blob/master/R/vl_plot.R#L31 and https://github.com/mdequeljoe/vl/blob/master/R/utils.R#L18)... in which case we'll want to credit @mdequeljoe  :smile:

**Comment by ijlyttle** [comment]
I think this is resolved in vegawidget
